### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by rutgercap** [sunkint/vue3-editor#3]
Hi! 

Is there some way to use this in Nuxt 3? I can't seem to get it working.
And if not, are there any plans to support Nuxt 3?

Thanks in advance!
R

**Comment by brambekkers** [comment]
You may have already succeeded. Nuxt 3 works fine for me with this version of the editor

**Comment by johnkingzy** [comment]
Hi @brambekkers, I'm curious to know how you went about using it? via modules in the nuxt.config.ts file?

**Comment by elhamzeinodini** [comment]
hi there, I get the following error although I follow all of the instructions in nuxt 3 : 
 ERROR  Cannot restart nuxt:  Cannot find module 'vue3-editor/nuxt'   14:14:50
Require stack:
- /home/elham/Downloads/termimnal101.frontend.backoffice.new/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:241025)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:259:29)
  at normalizeModule (node_modules/@nuxt/kit/dist/index.mjs:468:18)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:450:47)
  at initNuxt (node_modules/nuxt/dist/index.mjs:2469:13)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6843:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6737:10)

could you please tell me how can I get it to work  ?
